spring:
  messages:
      basename: "i18n/messages"
      encoding: UTF-8
question:
      bundleFilename: "question.FileName"
      regex: ","
main:
    locale: en_US
logging:
    level:
        root: info
        ru.get: debug
        org.springframework.web: info
        org.hibernate: error
    file:
        name: ./Logs/isBackend.log
    charset:
        console: UTF-8
        file: UTF-8